default_job = "check"

[jobs.check]
command = ["cargo", "check", "--profile=clif", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--profile=clif", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--profile=clif",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "test", "--color", "always",
    "--profile=clif",
    "--tests",
    "--", "--color", "always", # see https://github.com/Canop/bacon/issues/124
    "--quiet",
]
need_stdout = true

[jobs.covtest]
command = [
    "cargo", "llvm-cov", "--branch", "--open",
    "--color", "always", "--", "--color", "always",
]
need_stdout = true
on_success = "back"
allow_warnings = true
env.RUSTFLAGS = ""

[jobs.doc]
command = [
    "cargo", "doc", "--profile=clif", "--color", "always",
    "--no-deps", "--document-private-items",
]
need_stdout = false

[jobs.doc-open]
command = [
    "cargo", "doc", "--profile=clif", "--color", "always",
    "--no-deps", "--open", "--document-private-items",
]
need_stdout = false
on_success = "back"

[jobs.run]
command = [
    "cargo", "run",
    "--profile=clif",
    "--color", "always",
    "--",
    "--print=layout",
    "--print=codegen",
    "-o/tmp/main.S",
    "c/main.c",
]
need_stdout = true
allow_warnings = true
background = true
watch = ["../c"]
env.CLICOLOR_FORCE = "1"

[jobs.rebuild-tests]
command = ["touch", "panko/tests/testsuite/main.rs"]
need_stdout = false
on_success = "back"

[keybindings]
shift-t = "job:covtest"
shift-r = "job:rebuild-tests"
