[package]
name = "panko-codegen"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
indexmap = { workspace = true }
itertools = { workspace = true }
panko-lex = { path = "../panko-lex" }
panko-parser = { path = "../panko-parser" }
panko-sema = { path = "../panko-sema" }
