name: Δc

on:
  pull_request:

env:
  TERM: xterm-256color

jobs:
  delta-c:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-03-15
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: generate coverage
        run: |
          set -x

          git \
            clone https://github.com/narpfel/delta-c \
            --revision=e8e7dffd16c227f6308bb473a8b58cf4f1a89877

          python delta-c/Δc.py \
            --color=always \
            origin/"${{ github.base_ref }}" \
            origin/"${{ github.head_ref }}" \
            -- cargo llvm-cov --text --branch
