name: pre-commit

on:
  push:
    tags: '*'
    branches:
      - main
      - 'test-me-*'
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-10-28
          # we have to install rustc-codegen-cranelift here even though it’s
          # unused, otherwise it would get installed via `rust-toolchain.toml`
          # when running `cargo fmt`, which conflicts with the rust-toolchain
          # installed rust.
          components: rustfmt, clippy, rustc-codegen-cranelift
      - name: Install `cargo-insta`
        run: |
          curl -LsSf https://insta.rs/install.sh | sh
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files --hook-stage=manual"
